///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AutoInstall
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeleteReports recording.
    /// </summary>
    [TestModule("2767274b-a6dd-4c9f-8e2e-539006b6590a", ModuleType.Recording, 1)]
    public partial class DeleteReports : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AutoInstallRepository repository.
        /// </summary>
        public static AutoInstallRepository repo = AutoInstallRepository.Instance;

        static DeleteReports instance = new DeleteReports();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeleteReports()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeleteReports Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            DeleteReportDirectory("BiditemStructureReport.txt");
            Delay.Milliseconds(0);
            
            DeleteReportDirectory("BiditemStructureReportSimiliarContent.txt");
            Delay.Milliseconds(0);
            
            DeleteReportDirectory("bidlabormaterial.txt");
            Delay.Milliseconds(0);
            
            DeleteReportDirectory("BidLaborMaterialSimiliarContent.txt");
            Delay.Milliseconds(0);
            
            DeleteReportDirectory("ChiefEstimatorAnalysisReport.txt");
            Delay.Milliseconds(0);
            
            DeleteReportDirectory("ChiefEstimatorAnalysisReportSimiliarContent.txt");
            Delay.Milliseconds(0);
            
            DeleteReportDirectory("ConciseBidProposal.txt");
            Delay.Milliseconds(0);
            
            DeleteReportDirectory("ConciseBidProposalSimiliarContent.txt");
            Delay.Milliseconds(0);
            
            DeleteReportDirectory("CostPriceReport.txt");
            Delay.Milliseconds(0);
            
            DeleteReportDirectory("CostPriceReportSimiliarContent.txt");
            Delay.Milliseconds(0);
            
            DeleteReportDirectory("CostReport.txt");
            Delay.Milliseconds(0);
            
            DeleteReportDirectory("CostReportClassic.txt");
            Delay.Milliseconds(0);
            
            DeleteReportDirectory("CostReportClassicSimiliarContent.txt");
            Delay.Milliseconds(0);
            
            DeleteReportDirectory("CostReportSimiliarContent.txt");
            Delay.Milliseconds(0);
            
            DeleteReportDirectory("customizedbidproposal.txt");
            Delay.Milliseconds(0);
            
            DeleteReportDirectory("CustomizedBidProposalSimiliarContent.txt");
            Delay.Milliseconds(0);
            
            DeleteReportDirectory("EstimateRecapClassicSimiliarContent.txt");
            Delay.Milliseconds(0);
            
            DeleteReportDirectory("EstimateRecapReport.txt");
            Delay.Milliseconds(0);
            
            DeleteReportDirectory("EstimateRecapReportClassic.txt");
            Delay.Milliseconds(0);
            
            DeleteReportDirectory("EstimateRecapReportSimiliarContent.txt");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
