///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AutoInstall
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateDefaultPreference recording.
    /// </summary>
    [TestModule("92201f53-3f07-451d-b330-2d1b3ccd1b6b", ModuleType.Recording, 1)]
    public partial class ValidateDefaultPreference : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AutoInstallRepository repository.
        /// </summary>
        public static AutoInstallRepository repo = AutoInstallRepository.Instance;

        static ValidateDefaultPreference instance = new ValidateDefaultPreference();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateDefaultPreference()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateDefaultPreference Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.Tabs.ToolsTab' at Center.", repo.HeavyBidApp.Tabs.ToolsTabInfo, new RecordItemIndex(0));
            repo.HeavyBidApp.Tabs.ToolsTab.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.Preferences' at Center.", repo.HeavyBidApp.PreferencesInfo, new RecordItemIndex(1));
            repo.HeavyBidApp.Preferences.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBDropDownOptions.Estimate' at Center.", repo.HBDropDownOptions.EstimateInfo, new RecordItemIndex(2));
            repo.HBDropDownOptions.Estimate.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.EstimateEntry' at Center.", repo.HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.EstimateEntryInfo, new RecordItemIndex(3));
            repo.HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.EstimateEntry.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.CopyNotes'.", repo.HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.CopyNotesInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.CopyNotesInfo, "Checked", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Copy Notes') on item 'HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.CopyNotes'.", repo.HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.CopyNotesInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.CopyNotesInfo, "Text", "Copy Notes");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='False') on item 'HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.UseSourceMaterialRates'.", repo.HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.UseSourceMaterialRatesInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.UseSourceMaterialRatesInfo, "Checked", "False");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Use Source Material Rates') on item 'HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.UseSourceMaterialRates'.", repo.HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.UseSourceMaterialRatesInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.UseSourceMaterialRatesInfo, "Text", "Use Source Material Rates");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.Outline' at 11;207.", repo.HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.OutlineInfo, new RecordItemIndex(8));
            repo.HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.Outline.Click("11;207");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.ExternalPrograms' at Center.", repo.HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.ExternalProgramsInfo, new RecordItemIndex(9));
            repo.HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.ExternalPrograms.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='False') on item 'HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.UsePrimaveraIntegrationAPIWebServic'.", repo.HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.UsePrimaveraIntegrationAPIWebServicInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.UsePrimaveraIntegrationAPIWebServicInfo, "Checked", "False");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Use Primavera Integration API/Web Services') on item 'HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.UsePrimaveraIntegrationAPIWebServic'.", repo.HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.UsePrimaveraIntegrationAPIWebServicInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.UsePrimaveraIntegrationAPIWebServicInfo, "Text", "Use Primavera Integration API/Web Services");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.OKButton' at Center.", repo.HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.OKButtonInfo, new RecordItemIndex(12));
            repo.HBPopUpScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.OKButton.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
